# Generated by Django 4.2.6 on 2023-10-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newb', '0002_alter_accounts_aadhar_alter_accounts_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='acc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='bank_acc',
            field=models.IntegerField(max_length=14),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
