# Generated by Django 4.2.6 on 2023-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newb', '0003_alter_accounts_aadhar_alter_accounts_acc_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='bank_acc',
            field=models.BigIntegerField(max_length=14),
        ),
    ]
