# Generated by Django 4.2.6 on 2023-10-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newb', '0004_alter_accounts_bank_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='acc_name',
            new_name='name',
        ),
    ]
